# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# https://docs.microsoft.com/azure/devops/pipelines/ecosystems/android
pool:
  vmImage: 'macOS-10.13'

steps:

- task: FlutterInstall@0
  inputs:
    channel: 'stable'
    version: 'latest'

- task: FlutterBuild@0
  inputs:
    target: 'all'
    projectDirectory: '.'

- task: CopyFiles@2
  inputs:
    contents: '**/*.apk'
    targetFolder: '$(build.artifactStagingDirectory)'
- task: PublishBuildArtifacts@1