name: oltrace
description: An app for tracking shark fins and other products.

version: 1.6.0+1

environment:
  sdk: ">=2.7.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.0
  flutter_nfc_reader: ^0.1.0
  mobx: ^0.3.8
  flutter_mobx: ^0.3.3
  timeago: ^2.0.21
  geolocator: ^5.1.4+2
  sqflite: 1.1.7+2
  package_info: ^0.4.0+13
  shared_preferences: ^0.5.6
  collection: ^1.14.11
  maps_launcher: ^1.2.0
  flutter_svg: ^0.17.1
  path_provider: ^1.6.0
  dio: ^3.0.8
  flutter_picker: ^1.1.0
  uuid: ^2.0.4
  sentry: ^3.0.1
  qr_flutter: ^3.1.0
  esys_flutter_share: ^1.0.2
  gallery_saver: ^2.0.1
  olrac_themes:
    git: git@ssh.dev.azure.com:v3/Olrac/olrac_themes/olrac_themes
  url_launcher: ^5.4.5
  background_fetch: ^0.5.1
  connectivity: ^0.4.8+5
  imei_plugin: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.3.1
  mobx_codegen: ^0.3.9
  flutter_launcher_icons: ^0.7.4


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/launcher_icon.png"

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/fishing_methods/
    - assets/icons/sharks/
    - assets/icons/packaging/


  fonts:
    - family: RobotoLight
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
    - family: FiraSans
      fonts:
        - asset: assets/fonts/FiraSansCondensed-Regular.ttf

